---
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: kong
spec:
  template:
    spec:
      containers:
        - name: kong-migrations
          command: [ "/bin/sh", "-c", "kong migrations up" ]
          # command: [ "/bin/sh", "-c", "kong migrations finish" ]
      restartPolicy: OnFailure
