---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../katalog/kong/kong-enterprise-k8s

secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    behavior: replace
    files:
      - license=secrets/license.json
