# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../katalog/kong/kong-enterprise-k8s

patchesStrategicMerge:
  - service.yaml

secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    behavior: replace
    files:
      - license=secrets/license.json
  - name: kong-enterprise-k8s-docker
    namespace: kong
    behavior: replace
    files:
      - .dockerconfigjson=secrets/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson
