apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - kong-ingress-dbless.yaml
  - service.yaml

secretGenerator:
  - name: kong-settings
    namespace: kong
    envs:
      - kong.env

images:
  - name: kong
    newName: kong
    newTag: 2.3.2
  - name: ingress-controller
    newName: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
    newTag: 1.1.1