---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
      nodePort: 31081
      protocol: TCP
    - name: proxy-ssl
      port: 443
      targetPort: 8443
      nodePort: 31444
      protocol: TCP
  selector:
    app: ingress-kong

