apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-id
  annotations:
    kubernetes.io/ingress.class: 'kong'
config:
  header_name: my-request-id
plugin: correlation-id