---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-petstore
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: route-customization
    konghq.com/plugins: request-id,rate-limiting,prometheus
spec:
  rules:
    - http:
        paths:
          - path: /pet
            backend:
              serviceName: petstore
              servicePort: 8080
