---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-petstore-2
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: request-id,rate-limiting,prometheus
    konghq.com/override: route-customization
spec:
  rules:
    - host: awesome-kong.io
      http:
        paths:
          - path: /store
            backend:
              serviceName: petstore
              servicePort: 8080
