apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      imagePullSecrets:
      - name: kong-enterprise-k8s-docker
      containers:
      - name: proxy
        env:
        - name: KONG_LICENSE_DATA
          valueFrom:
            secretKeyRef:
              name: kong-enterprise-license
              key: license
