apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kong-dbless

patchesStrategicMerge:
  - kong-enterprise-k8s.yaml

images:
  - name: registry.sighup.io/fury/kong
    newName: docker.io/kong/kong-gateway
    newTag: 2.4.1.1

secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    files:
      - license=secrets/license.json
