# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: proxy-ssl
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: ingress-kong-dp
---
apiVersion: v1
kind: Service
metadata:
  name: kong-portal
  namespace: kong
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: portal
      port: 80
      protocol: TCP
      targetPort: 8003
    - name: portal-api
      port: 8080
      protocol: TCP
      targetPort: 8004
    - name: portal-ssl
      port: 443
      protocol: TCP
      targetPort: 8446
    - name: portal-api-ssl
      port: 8443
      protocol: TCP
      targetPort: 8447
  selector:
    app: ingress-kong-dp
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: admin
      port: 8080
      protocol: TCP
      targetPort: 8001
    - name: manager
      port: 80
      protocol: TCP
      targetPort: 8002
    - name: admin-ssl
      port: 8443
      protocol: TCP
      targetPort: 8444
    - name: manager-ssl
      port: 443
      protocol: TCP
      targetPort: 8445
  selector:
    app: ingress-kong-cp
