---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ingress-kong
  name: ingress-kong
  namespace: kong
spec:
  selector:
    matchLabels:
      app: ingress-kong
  template:
    metadata:
      annotations:
        kuma.io/gateway: enabled
        prometheus.io/port: "8100"
        prometheus.io/scrape: "true"
        traffic.sidecar.istio.io/includeInboundPorts: ""
      labels:
        app: ingress-kong
    spec:
      initContainers:
        - command:
            - /bin/sh
            - -c
            - while true; do kong migrations list; if [[ 0 -eq $? ]]; then exit 0; fi;
              sleep 2;  done;
          env:
            - name: KONG_LICENSE_DATA
              valueFrom:
                secretKeyRef:
                  key: license
                  name: kong-enterprise-license
          envFrom:
            - secretRef:
                name: kong-settings
            - secretRef:
                name: kong-settings-cp
          image: kong
          name: wait-for-migrations
      serviceAccountName: kong-serviceaccount
      containers:
        - name: ingress-controller
          $patch: delete
        - name: proxy
          envFrom:
            - secretRef:
                name: kong-settings
            - secretRef:
                name: kong-settings-dp
          env:
            - name: KONG_LICENSE_DATA
              valueFrom:
                secretKeyRef:
                  key: license
                  name: kong-enterprise-license
          ports:
            - containerPort: 8000
              name: proxy
              protocol: TCP
            - containerPort: 8443
              name: proxy-ssl
              protocol: TCP

            - containerPort: 8100
              name: metrics
              protocol: TCP

            - containerPort: 8001
              name: admin
              protocol: TCP
            - containerPort: 8444
              name: admin-ssl
              protocol: TCP

            - containerPort: 8002
              name: admin-gui
              protocol: TCP
            - containerPort: 8445
              name: admin-gui-ssl
              protocol: TCP

            - containerPort: 8003
              name: portal-gui
              protocol: TCP
            - containerPort: 8446
              name: portal-gui-ssl
              protocol: TCP

            - containerPort: 8004
              name: api-gui
              protocol: TCP
            - containerPort: 8447
              name: api-ssl
              protocol: TCP