apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: # Labels and name of the ServiceMonitor
  labels:
    app: ingress-kong
  name: ingress-kong
  namespace: kong
spec:
  endpoints: # which port of the pods to scrape
    - interval: 10s
      port: metrics
  jobLabel: ingress-kong-metrics
  namespaceSelector: # filtering namespace
    matchNames:
      - kong
  selector: # pod labels to match
    matchLabels:
      app: ingress-kong-dp
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-kong-metrics
  labels:
    app: ingress-kong-dp
  namespace: kong
spec:
  selector:
    app: ingress-kong-dp
  ports:
    - name: metrics
      port: 9542
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: # Labels and name of the ServiceMonitor
  labels:
    app: ingress-kong
  name: ingress-kong-cp
  namespace: kong
spec:
  endpoints: # which port of the pods to scrape
    - interval: 10s
      port: metrics
  jobLabel: ingress-kong-metrics-cp
  namespaceSelector: # filtering namespace
    matchNames:
      - kong
  selector: # pod labels to match
    matchLabels:
      app: ingress-kong-cp
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-kong-metrics-cp
  labels:
    app: ingress-kong-cp
  namespace: kong
spec:
  selector:
    app: ingress-kong-cp
  ports:
    - name: metrics
      port: 9542
      targetPort: metrics
